apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: {{.TargetNamespace}}
  name: etcd-quorum-guard
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: etcd-quorum-guard
